DROP TABLE IF EXISTS [RecipeBook].[dbo].Products

CREATE TABLE [RecipeBook].[dbo].Products (
ProdID int identity (1,1),
ProdName varchar(30),
PRIMARY KEY(ProdID)
);

INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Salt')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Black Pepper')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Rosemary')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Sage')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Thyme')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Oregano')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Bay Leaves')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Nutmeg')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Brown Sugar')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('White Sugar')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Castor Sugar')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Butter')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Milk')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Cream')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Buttermilk')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Rice Bubbles')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Cornflakes')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Tinned Salmon')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Fresh Fish')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Fresh Chicken')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Turkey')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Chuck Steak')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Plain Flour')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Wholemeal Flour')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Cornflour')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Self-Raising Flour')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Breadcrumbs')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Water')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Mustard')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Olive Oil')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Cooking Oil')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Potatoes')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Carrots')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Pumpkin')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Beets')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Peas')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Onions')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Truffles')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Spaghetti')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Syrup')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Bi-Carb Soda')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Cocoa')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Dried Coconut')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Bananas')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Eggs')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Lemon Juice')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Cinnamon')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Apples')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Vanilla Essence')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Pineapple Chunks')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Rolled Oats')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Tomato Sauce')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Bacon')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Tomatoes')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Tomato Paste')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Minced Pork')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Garlic Cloves')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Basil')
INSERT [RecipeBook].[dbo].[Products] ([ProdName]) VALUES ('Mushrooms')


