DROP TABLE IF EXISTS [RecipeBook].[dbo].Recipes

CREATE TABLE [RecipeBook].[dbo].Recipes (
RecipeID int,
Name varchar(30),
Method text,
CookTime float,
CookTemp int,
Category smallint);

INSERT [RecipeBook].[dbo].[Recipes] ([RecipeID], [Name], [Method], [CookTime], [CookTemp], [Category]) VALUES (1, 'Anzac Cookies', 'Melt butter and golden syrup together. Boil water and mix in bi-carbonate soda. Add to butter mixture and stir. Place all dry ingredients into a large bowl and then stir through the butter and syrup mixture. Measure teaspoonfuls of biscuit dough and place onto a greased baking tray. Leave room between them. Allow to cool when done, then place on wire racks.', 20, 150, 9)
INSERT [RecipeBook].[dbo].[Recipes] ([RecipeID], [Name], [Method], [CookTime], [CookTemp], [Category]) VALUES (2, 'Cornflake Biscuits', 'Cream butter and sugar, then mix through egg. Stir in cornflakes, coconut and flour. Spoon onto biscuit tray and place on greased baking tray. Allow to cool when done, then place on wire racks.', 15, 180, 9)
INSERT [RecipeBook].[dbo].[Recipes] ([RecipeID], [Name], [Method], [CookTime], [CookTemp], [Category]) VALUES (3, 'Chocolate Slice', 'Mix sugar, cornflakes, cocoa, coconut and flour together. Melt butter into syrup and pour over dry ingredient mix. Press into a medium-depth baking tray. When cooked, slice while still warm.', 30, 180, 9)
INSERT [RecipeBook].[dbo].[Recipes] ([RecipeID], [Name], [Method], [CookTime], [CookTemp], [Category]) VALUES (4, 'Chocolate Sponge Cake', 'Separate eggs. Beat egg-whites until stiff, then mix in sugar. Next, gradually add egg yolks one at a time while mixing slowly. Sift flour two or three times, and fold into egg/sugar mixture. Boil water, then dissolve butter and cocoa into it. Stir into cake mix. Place mixture into cake tins and bake.', 20, 180, 4)
INSERT [RecipeBook].[dbo].[Recipes] ([RecipeID], [Name], [Method], [CookTime], [CookTemp], [Category]) VALUES (5, 'Tea Cake', 'Mix flour, salt, brown sugar, cinnamon and nutmeg together in a bowl. Melt butter and mix with beaten egg, milk and lemon juice. Stir into dry ingredients and beat until smooth. Pour mixture into a greaded and floured loaf tin. Mix white sugar and extra 1/2 teaspoon cinnamon and sprinkle over top of cake mixture. Bake until golden brown. Serve with butter.', 35, 180, 4)
INSERT [RecipeBook].[dbo].[Recipes] ([RecipeID], [Name], [Method], [CookTime], [CookTemp], [Category]) VALUES (6, 'Apple Crumble', 'Cover apples with water and stew for 30 minutes. Rub butter into flour and sugar until mixture has texture of breadcrumbs. Add nutmeg and cinnamon and mix through. Remove apples from water and mash with potato-masher. Mix apples through dry mixture and spread onto a baking tray. Bake until golden brown. Serve with whipped cream.', 15, 180 , 5)
INSERT [RecipeBook].[dbo].[Recipes] ([RecipeID], [Name], [Method], [CookTime], [CookTemp], [Category]) VALUES (7, 'Baked Custard', 'Beat eggs and sugar until fluffy, but not stiff. Stir in milk and a few drops of vanilla essence. Pour mixture into a cassserole dish and place a few small chunks of butter on top. Stand dish in larger pan of water and bake.', 75, 180, 5)
INSERT [RecipeBook].[dbo].[Recipes] ([RecipeID], [Name], [Method], [CookTime], [CookTemp], [Category]) VALUES (8, 'Chocolate Banana Pudding', 'Cream butter and sugar together, then add cocoa, milk and flour and mix through. Slice bananas and layer over bottom of a greased pie dish. Sprinkle with castor sugar and lemon juice. Pour cake mixture over bananas and bake until set.', 30, 180, 5)
INSERT [RecipeBook].[dbo].[Recipes] ([RecipeID], [Name], [Method], [CookTime], [CookTemp], [Category]) VALUES (9, 'Salmon Pineapple', 'Make a white sauce with flour, milk and half of the butter. Drain salmon making sure to remove bones. Add to white sauce and season with salt and pepper. Drain the pineapple chunks. Layer one third of the salmon mixture into a baking dish, followed by a layer of pineapple. Repeat with a second layer of the salmon mixture, then another of pineapple, then remaining salmon mixture. Melt remaining butter in a frying pan and toast cornflakes until well coated. Spread cornflakes over salmon and pineapple mix. Cook until golden brown.', 20, 175, 6)
INSERT [RecipeBook].[dbo].[Recipes] ([RecipeID], [Name], [Method], [CookTime], [CookTemp], [Category]) VALUES (10, 'Salmon Patties', 'Make a batter using flour, egg, salt and milk. Grate onion and mix through. Drain salmon and add. Mix all ingredients and form into patties. Shallow fry in hot oil. Serve with potato chips and/or grilled tomatoes.', 5, 250, 6)
INSERT [RecipeBook].[dbo].[Recipes] ([RecipeID], [Name], [Method], [CookTime], [CookTemp], [Category]) VALUES (11, 'Chuck Steak Casserole', 'Cut rolled beef into cubes approximately 1.5cm. Place in casserole dish. Mix mustard, water, salt, pepper and flour together and pour over cubed meat. Cook until meat is tender.', 120, 180, 1)
INSERT [RecipeBook].[dbo].[Recipes] ([RecipeID], [Name], [Method], [CookTime], [CookTemp], [Category]) VALUES (12, 'Scrambled Eggs', 'Place milk and butter into a saucepan and bring to boil on stove-top. Crack eggs into a bowl and whisk through with salt and pepper to taste. Mix eggs into milk and butter and stir over a low heat until set. Serve with toast, bacon and grilled tomatoes.', 10, 150, 10)
INSERT [RecipeBook].[dbo].[Recipes] ([RecipeID], [Name], [Method], [CookTime], [CookTemp], [Category]) VALUES (13, 'Eggs ala Steve', 'Cook eggs in a pan. Grill bacon and tomatoes. Serve with a glass of bourbon.', 15, 20, 9)
INSERT [RecipeBook].[dbo].[Recipes] ([RecipeID], [Name], [Method], [CookTime], [CookTemp], [Category]) VALUES (14, 'Spaghetti Bolognese', 'Crush garlic cloves and dice onion. Fry garlic and onion in oil until onion is clear in colour. Add pork mince and stir until meat is pink-brown. Stir in tomato paste, salt, pepper, basil and oregano. Chop tomato, mushrooms and bacon. Mix in with pork. Fill tomato paste tin with water and stir through. Bring pork mixture to boil, cover and leave to simmer on low heat for approx 30 minutes. Cook spaghetti in saucepan of hot, salted water for 12 to 15 minutes. Drain spaghetti, swirl onto plate and pile meat sauce on top. Serve with grated parmesan reggio cheese.', 35, 120, 7)
